In [11]:
from urllib.request import Request, urlopen
from bs4 import BeautifulSoup
import pandas as pd

def scrape_SO_tags():
    
    '''Downloads a csv file that consist of colums:
    -Tag Names : Tag Names of the Popular Tags
    -Tag Count : Count of particular Tags
    -Asked_Today : Count of questions asked today with that tag
    -Asked_This_Week: Count of questions asked over a week with that tag
    '''
   
    site= "https://stackoverflow.com/tags?tab=popular"
    hdr = {'User-Agent': 'Mozilla/5.0'}
    req = Request(site,headers=hdr)
    page = urlopen(req)
    soup = BeautifulSoup(page)
    
    #Getting data into a dictionary
    dictionary={"Tag Names":[],"Tag_Count":[], "Asked_Today":[], "Asked_This_Week":[]}
    
    #Extracting The Popular Tags
    for tag in soup.find_all("a",class_="post-tag"): 
        dictionary["Tag Names"].append(tag.text)
    
    #Extracting The Counts
    for tag_count in soup.find_all("div",class_="mt-auto grid jc-space-between fs-caption fc-black-400"):
        
        
        x=tag_count.text
        string_split=x.split()

        #Getting the Tag_Count
        dictionary["Tag_Count"].append(int(string_split[0]))
        
        #Questions asked today with this tag
        dictionary["Asked_Today"].append((string_split[2]))
        
        #Questions asked over a week with this tag
        dictionary["Asked_This_Week"].append(int(string_split[5]))
 
    
    #Returning a DataFrame
    df=pd.DataFrame(dictionary)
    df.index+=1
    
    return df

df=scrape_SO_tags()
df.to_excel(r"C:\Users\shrut\Data_Analytics_Portfolio\Web_Scrapping_Projects\Stack_Overflow_Popular_Tags\PopularSOTags.xlsx")
print("Update Successful")

Update Successful

In [6]:
df

        Tag Names  Tag_Count Asked_Today  Asked_This_Week
1      javascript    2206829         848             5287
2            java    1770612         486             2888
3          python    1705712        1299             7628
4              c#    1475581         326             1958
5             php    1400612         293             1789
6         android    1332704         300             1834
7            html    1066841         349             2125
8          jquery    1011100         117              698
9             c++     722150         234             1405
10            css     714997         243             1335
11            ios     654635          94              628
12          mysql     623349         174              915
13            sql     588065         213             1171
14              r     399417         232             1473
15        node.js     383891         232             1497
16        asp.net     362490          41              212
17         arrays     362040         125              839
18              c     357169         123              750
19  ruby-on-rails     325670          53              228
20           json     316896         130              708
21           .net     307475          64              336
22     sql-server     303214          67              418
23        reactjs     300087         358             2299
24          swift     294575         109              678
25    objective-c     291596          18               70
26     python-3.x     282030         281             1411
27         django     264364         159              879
28      angularjs     262133           6               53
29        angular     251458         169              896
30          excel     244850          95              525
31          regex     239569          60              407
32         iphone     221027           7               38
33           ruby     219137          36              158
34           ajax     215536          37              221
35          linux     203992          84              504
36            xml     201562          37              264